services:
  postgres:
    ports: !reset []

  backend:
    build:
      target: final
    volumes: []
    working_dir: /app
    command: []
    ports: !reset []
    networks:
      - habithub-network
      - web

  frontend:
    build:
      context: ./frontend
      target: final
      args:
        - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - web

networks:
  web:
    external: true
