name: Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/staging'
    runs-on: [self-hosted, staging]
    steps:
      - name: Pull & redeploy
        run: |
          cd $STAGING_DEPLOY_PATH
          git pull
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
          docker exec nginx nginx -s reload

  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, production]
    steps:
      - name: Pull & redeploy
        run: |
          cd $PROD_DEPLOY_PATH
          git pull
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
          docker exec nginx nginx -s reload
